name: SSH into container

on: [push]

env:
  SSH_PORT: 22
  SSH_USERNAME: chelin

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/centos:7

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        sudo yum update -y && sudo yum install -y openssh-server
        echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
        echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
        sudo service sshd restart
        echo "${{ secrets.SSH_PASSWORD }}" | sudo passwd "${{ env.SSH_USERNAME }}" --stdin

    - name: Get container IP and SSH port
      id: job_info
      run: |
        CONTAINER_ID=$(docker ps -qf name=$GITHUB_WORKFLOW | head -n1)
        IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_ID)
        echo "::set-output name=ip::$IP"
        echo "::set-output name=port::$SSH_PORT"

    - name: SSH into container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ steps.job_info.outputs.ip }}
        username: ${{ env.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ steps.job_info.outputs.port }}
        script: |
          # 运行任意命令或操作
          echo "Hello, world!"
