name: SSH into container

on: 
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  SSH_PORT: 22
  SSH_USERNAME: root

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/centos:7

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Debug Session
      uses: P3TERX/ssh2actions@main
      env:
         TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
         TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
