name: Build WebRTC

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  #  branches:
  #    - main
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
    
permissions:
  contents: read

env:
  PLATFORM: linux64
  WEBRTC_BRANCH: branch-heads/4664
  DEPOT_TOOLS_PATH: /usr/local/webrtc
  BUILD_PATH: /tmp/webrtc-build

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
      - uses: actions/checkout@v2
      #- name: Setup Debug Session
      #  uses: P3TERX/ssh2actions@main
      #if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      #  env:
      #    TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
       #   TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          
      - name: Install dependencies
        run: |
          yum -y update
          yum install -y centos-release-scl-rh
          yum install -y devtoolset-10-gcc*

     
      - name: Build project with GCC 10
        run: |
          scl enable devtoolset-10 'gcc -v'
          
      - name: Build project with GCC 10  2
        run: |
          scl enable devtoolset-10 bash
          gcc -v
