name: Build WebRTC

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  #  branches:
  #    - main
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
    
permissions:
  contents: read

env:
  PLATFORM: linux64
  WEBRTC_BRANCH: branch-heads/4664
  DEPOT_TOOLS_PATH: /usr/local/webrtc
  BUILD_PATH: /tmp/webrtc-build

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
      - uses: actions/checkout@v2
      #- name: Setup Debug Session
      #  uses: P3TERX/ssh2actions@main
      #if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      #  env:
      #    TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
       #   TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          
      - name: Install dependencies
        run: |
          yum -y update
          yum install -y centos-release-scl-rh
          yum install -y devtoolset-10-gcc*

     
      - name: Build project with GCC 10
        run: |
          echo "gcc -v" > build_script.sh
          echo "cd ${{ env.DEPOT_TOOLS_PATH }}" >> build_script.sh
          echo "export PATH=${{ env.DEPOT_TOOLS_PATH }}/depot_tools:${PATH}" >> build_script.sh
          echo "fetch --nohooks webrtc" >> build_script.sh
          echo "cd src" > build_script.sh
          echo "git checkout branch-heads/4664" >> build_script.sh
          echo "'start build'" >> build_script.sh
          echo "pwd" >> build_script.sh
          echo "ls -al" >> build_script.sh
          echo "git branch" >> build_script.sh
          echo "gn gen out/Release --args='target_os="linux" target_cpu="x64" fatal_linker_warnings=false is_debug=false is_component_build=false use_sysroot=false is_clang=false use_lld=false treat_warnings_as_errors=false rtc_include_tests=true rtc_build_examples=false use_custom_libcxx=false use_rtti=true'" >> build_script.sh
          echo "'start make'" >> build_script.sh
          echo "ninja -C out/Release   " >> build_script.sh
          chmod +x build_script.sh
          echo "****************************"
          cat ./build_script.sh
          echo "****************************"
